// <auto-generated />
using System;
using MerdasGold.Features.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerdasGold.Features.Persistence.Migrations
{
    [DbContext(typeof(MerdasGoldDbContext))]
    partial class MerdasGoldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MerdasGold.Features.Authentication.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int?>("PrimaryCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PrimaryCategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Product", null, t =>
                        {
                            t.HasCheckConstraint("CK_Product_Status", "[Status] IN (N'draft',N'active',N'archived')");
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductAttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductAttributeDefinition", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductAttributeDefinition_DataType", "[DataType] IN (N'text',N'number',N'boolean',N'select',N'color')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "purity",
                            DataType = "select",
                            IsActive = true,
                            Name = "عیار",
                            Unit = ""
                        },
                        new
                        {
                            Id = 2,
                            Code = "gold-color",
                            DataType = "color",
                            IsActive = true,
                            Name = "رنگ طلا",
                            Unit = ""
                        },
                        new
                        {
                            Id = 3,
                            Code = "size",
                            DataType = "number",
                            IsActive = true,
                            Name = "سایز",
                            Unit = ""
                        },
                        new
                        {
                            Id = 4,
                            Code = "stone-type",
                            DataType = "text",
                            IsActive = true,
                            Name = "نوع نگین",
                            Unit = ""
                        },
                        new
                        {
                            Id = 5,
                            Code = "style",
                            DataType = "text",
                            IsActive = true,
                            Name = "سبک طراحی",
                            Unit = ""
                        },
                        new
                        {
                            Id = 6,
                            Code = "length",
                            DataType = "number",
                            IsActive = true,
                            Name = "طول",
                            Unit = "سانتی‌متر"
                        },
                        new
                        {
                            Id = 7,
                            Code = "material",
                            DataType = "text",
                            IsActive = true,
                            Name = "جنس",
                            Unit = ""
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductAttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId", "Value")
                        .IsUnique();

                    b.ToTable("ProductAttributeOption", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "۱۸ عیار",
                            Value = "18"
                        },
                        new
                        {
                            Id = 2,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "۲۴ عیار",
                            Value = "24"
                        },
                        new
                        {
                            Id = 3,
                            AttributeDefinitionId = 2,
                            ColorHex = "#D4AF37",
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "طلایی",
                            Value = "gold"
                        },
                        new
                        {
                            Id = 4,
                            AttributeDefinitionId = 2,
                            ColorHex = "#B76E79",
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "رزگلد",
                            Value = "rose-gold"
                        },
                        new
                        {
                            Id = 5,
                            AttributeDefinitionId = 2,
                            ColorHex = "#D9D9D6",
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "سفید",
                            Value = "white-gold"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductAttributeValue", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ProductId", "AttributeDefinitionId");

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("ProductAttributeValue", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "زیورآلات",
                            Slug = "jewelry"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "انگشتر",
                            ParentId = 1,
                            Slug = "rings"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "گردنبند",
                            ParentId = 1,
                            Slug = "necklaces"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "دستبند",
                            ParentId = 1,
                            Slug = "bracelets"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "گوشواره",
                            ParentId = 1,
                            Slug = "earrings"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "پلاک و آویز",
                            ParentId = 1,
                            Slug = "pendants"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "سرویس و نیم‌ست",
                            ParentId = 1,
                            Slug = "sets"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "سکه و شمش",
                            Slug = "coins-bars"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExactGoldWeightGrams")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("StoneWeightCarats")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.ToTable("ProductPiece", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductPiece_Status", "[Status] IN (N'available',N'reserved',N'sold',N'damaged')");

                            t.HasCheckConstraint("CK_ProductPiece_Weight", "[ExactGoldWeightGrams] > 0");
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "جدید",
                            Slug = "new"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "پرفروش",
                            Slug = "best-seller"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "پیشنهاد ویژه",
                            Slug = "special"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "مناسب هدیه",
                            Slug = "gift"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductTagLink", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ProductTagId");

                    b.HasIndex("ProductTagId");

                    b.ToTable("ProductTagLink", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("ProductType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "انگشتر طلا"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "گردنبند"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "دستبند"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "گوشواره"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "پلاک و آویز"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "سرویس و نیم‌ست"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "سکه و شمش"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IsActive = true,
                            IsSystem = true,
                            Name = "کالای عمومی"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductTypeAttribute", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsComparable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductTypeId", "AttributeDefinitionId");

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("ProductTypeAttribute", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductTypeAttribute_Scope", "[Scope] IN (N'product',N'variant')");
                        });

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeDefinitionId = 2,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeDefinitionId = 3,
                            DisplayOrder = 3,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeDefinitionId = 4,
                            DisplayOrder = 4,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeDefinitionId = 5,
                            DisplayOrder = 5,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeDefinitionId = 2,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeDefinitionId = 6,
                            DisplayOrder = 3,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeDefinitionId = 4,
                            DisplayOrder = 4,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeDefinitionId = 2,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeDefinitionId = 3,
                            DisplayOrder = 3,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeDefinitionId = 2,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeDefinitionId = 4,
                            DisplayOrder = 3,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 5,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 5,
                            AttributeDefinitionId = 2,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 6,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 6,
                            AttributeDefinitionId = 2,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "variant"
                        },
                        new
                        {
                            ProductTypeId = 7,
                            AttributeDefinitionId = 1,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = true,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 7,
                            AttributeDefinitionId = 7,
                            DisplayOrder = 2,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "product"
                        },
                        new
                        {
                            ProductTypeId = 8,
                            AttributeDefinitionId = 7,
                            DisplayOrder = 1,
                            IsComparable = true,
                            IsFilterable = true,
                            IsRequired = false,
                            Scope = "product"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("[Barcode] <> N''");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("[Sku] <> N''");

                    b.ToTable("ProductVariant", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductVariantAttributeValue", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ProductVariantId", "AttributeDefinitionId");

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("ProductVariantAttributeValue", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Content.Entities.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("FaqItem", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Content.Entities.PromotionBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Placement", "DisplayOrder");

                    b.ToTable("PromotionBanner", null, t =>
                        {
                            t.HasCheckConstraint("CK_PromotionBanner_Placement", "[Placement] IN (N'home-slider', N'home-banner')");
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Content.Entities.StorePolicy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("StorePolicy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "",
                            DisplayOrder = 1,
                            IsPublished = false,
                            Key = "store-rules",
                            Summary = "",
                            Title = "قوانین فروشگاه"
                        },
                        new
                        {
                            Id = 2,
                            Content = "",
                            DisplayOrder = 2,
                            IsPublished = false,
                            Key = "shipping",
                            Summary = "",
                            Title = "شیوه ارسال"
                        },
                        new
                        {
                            Id = 3,
                            Content = "",
                            DisplayOrder = 3,
                            IsPublished = false,
                            Key = "payments",
                            Summary = "",
                            Title = "روش‌های پرداخت"
                        },
                        new
                        {
                            Id = 4,
                            Content = "",
                            DisplayOrder = 4,
                            IsPublished = false,
                            Key = "returns",
                            Summary = "",
                            Title = "شرایط مرجوعی"
                        },
                        new
                        {
                            Id = 5,
                            Content = "",
                            DisplayOrder = 5,
                            IsPublished = false,
                            Key = "privacy",
                            Summary = "",
                            Title = "حریم خصوصی و تعهدات حقوقی"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Diagnostics.Entities.ApplicationError", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(24000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("TraceId");

                    b.HasIndex("Source", "StatusCode", "OccurredUtc");

                    b.ToTable("ApplicationErrors", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.OperationLogs.Entities.OpLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OperationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OperationDateTime");

                    b.HasIndex("UserId");

                    b.ToTable("OpLog", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Pricing.Entities.GoldRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PriceToman")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SourceUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedUtc");

                    b.HasIndex("Provider", "IsValid", "Id");

                    b.ToTable("GoldRates", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Pricing.Entities.PriceDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Value")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "StartsUtc", "EndsUtc");

                    b.ToTable("PriceDiscounts", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Pricing.Entities.PricingRule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FeeMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("FeeValue")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<string>("InvoiceFooter")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ProfitPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("RoundToToman")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.ToTable("PricingRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeeMode = "percent",
                            FeeValue = 0m,
                            InvoiceFooter = "از اعتماد شما سپاسگزاریم.",
                            ProfitPercent = 0m,
                            RoundToToman = 1m,
                            TaxPercent = 0m
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Pricing.Entities.RateSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ManualExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ManualPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<int>("MaxAgeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ProtectedApiKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("RateSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = false,
                            IntervalMinutes = 5,
                            MaxAgeMinutes = 10,
                            ProtectedApiKey = "",
                            Provider = "Navasan",
                            SourceUnit = "toman"
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.Settings.Entities.SecuritySettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LockoutDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxFailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPasswordLength")
                        .HasColumnType("int");

                    b.Property<bool>("RequireDigit")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireLowercase")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSpecialCharacter")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireUppercase")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SecuritySettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_SecuritySettings_LockoutDurationMinutes", "[LockoutDurationMinutes] BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("CK_SecuritySettings_MaxFailedLoginAttempts", "[MaxFailedLoginAttempts] BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_SecuritySettings_MinimumPasswordLength", "[MinimumPasswordLength] BETWEEN 6 AND 128");

                            t.HasCheckConstraint("CK_SecuritySettings_SessionTimeoutMinutes", "[SessionTimeoutMinutes] BETWEEN 5 AND 10080");

                            t.HasCheckConstraint("CK_SecuritySettings_SingleRow", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LockoutDurationMinutes = 15,
                            MaxFailedLoginAttempts = 5,
                            MinimumPasswordLength = 12,
                            RequireDigit = true,
                            RequireLowercase = true,
                            RequireSpecialCharacter = true,
                            RequireUppercase = true,
                            SessionTimeoutMinutes = 60
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.StoreInformation.Entities.StoreBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("StoreBankAccount", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.StoreInformation.Entities.StoreLocation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ZoomLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreLocation", null, t =>
                        {
                            t.HasCheckConstraint("CK_StoreLocation_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_StoreLocation_Longitude", "[Longitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_StoreLocation_SingleRow", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Latitude = 35.689200m,
                            Longitude = 51.389000m,
                            ZoomLevel = 13
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.StoreInformation.Entities.StoreProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ActivityStartDate")
                        .HasColumnType("date");

                    b.Property<string>("BusinessCategory")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FaviconContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("FaviconData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FaviconFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("StoreProfile", null, t =>
                        {
                            t.HasCheckConstraint("CK_StoreProfile_SingleRow", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessCategory = "طلا و جواهر",
                            EnglishName = "Merdas Gold",
                            IsActive = true,
                            Name = "مرداس گلد",
                            ShortDescription = "",
                            Tagline = ""
                        });
                });

            modelBuilder.Entity("MerdasGold.Features.StoreInformation.Entities.StoreWorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DayOrder")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("DayOrder")
                        .IsUnique();

                    b.ToTable("StoreWorkingHour", null, t =>
                        {
                            t.HasCheckConstraint("CK_StoreWorkingHour_DayOrder", "[DayOrder] BETWEEN 0 AND 6");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayName = "شنبه",
                            DayOrder = 0,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsOpen = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayName = "یکشنبه",
                            DayOrder = 1,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsOpen = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayName = "دوشنبه",
                            DayOrder = 2,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsOpen = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayName = "سه‌شنبه",
                            DayOrder = 3,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsOpen = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayName = "چهارشنبه",
                            DayOrder = 4,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsOpen = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayName = "پنجشنبه",
                            DayOrder = 5,
                            EndTime = new TimeOnly(18, 0, 0),
                            IsOpen = true,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayName = "جمعه",
                            DayOrder = 6,
                            IsOpen = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.Product", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductCategory", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryCategory");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductAttributeOption", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductAttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductAttributeValue", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductAttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerdasGold.Features.Catalog.Entities.Product", "Product")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductCategory", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductImage", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductPiece", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductVariant", "ProductVariant")
                        .WithMany("Pieces")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductTagLink", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.Product", "Product")
                        .WithMany("Tags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductTag", "ProductTag")
                        .WithMany()
                        .HasForeignKey("ProductTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductTag");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductTypeAttribute", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductAttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductVariant", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductVariantAttributeValue", b =>
                {
                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductAttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerdasGold.Features.Catalog.Entities.ProductVariant", "ProductVariant")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MerdasGold.Features.Authentication.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MerdasGold.Features.Authentication.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerdasGold.Features.Authentication.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MerdasGold.Features.Authentication.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.Product", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("Images");

                    b.Navigation("Tags");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MerdasGold.Features.Catalog.Entities.ProductVariant", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("Pieces");
                });
#pragma warning restore 612, 618
        }
    }
}
